services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: pnpm run dev -- --host
    ports:
      - 5173:5173